<template>
  <div>
    <button class="apple-btn apple-btn-secondary" @click="openModal">
      <i class="bi bi-file-earmark-arrow-up me-1"></i> Import CSV
    </button>

    <div class="modal fade" id="importCSVModal" tabindex="-1" ref="modal">
      <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content apple-modal">
          
          <div class="modal-header border-0 pb-0">
            <h5 class="modal-title apple-title">Import CSV</h5>
            <button type="button" class="btn-close apple-close-btn" data-bs-dismiss="modal"></button>
          </div>
          
          <div class="modal-body pt-3">
            
            <div v-if="!previewData">
              <div class="apple-callout apple-callout-info mb-4">
                <i class="bi bi-info-circle-fill me-2"></i>
                <span>Skay exports are processed automatically. For traditional banking statement uploads, you will map your target ledger account in the next step.</span>
              </div>
              
              <div class="mb-4">
                <label class="apple-label">CSV File</label>
                <div class="apple-file-input-wrapper">
                  <input type="file" class="form-control apple-input" @change="handleFileUpload" accept=".csv">
                </div>
              </div>
              
              <div class="accordion apple-accordion mb-3" id="csvGuideAccordion">
                <div class="accordion-item bg-transparent border-0">
                  <h2 class="accordion-header">
                    <button class="accordion-button collapsed apple-accordion-trigger" type="button" data-bs-toggle="collapse" data-bs-target="#guideCollapse">
                      <i class="bi bi-question-circle me-2"></i> View CSV requirements & specifications
                    </button>
                  </h2>
                  <div id="guideCollapse" class="accordion-collapse collapse" data-bs-parent="#csvGuideAccordion">
                    <div class="accordion-body apple-accordion-content">
                      <div class="mb-3">
                        <span class="apple-badge mb-2">Skay Standard Layout</span>
                        <p class="mb-0 apple-desc">Requires exactly 6 specific data headers: <code>date</code>, <code>description</code>, <code>amount</code>, <code>type</code> (income/expense), <code>category</code>, <code>account</code>.</p>
                      </div>
                      
                      <div class="pt-2">
                        <p class="mb-2 apple-desc">The systemic parser auto-detects and binds the primitive columns:</p>
                        <ul class="ps-3 mb-2 apple-desc">
                          <li><strong>Accepted dates:</strong> data, date, booking date, value date.</li>
                          <li><strong>Accepted amounts:</strong> amount, money in/out (the - / + metrics inherently dictate structural directional balance).</li>
                        </ul>
                        <p class="apple-text-warning small mt-2 mb-0">
                          <i class="bi bi-exclamation-triangle-fill me-1"></i> Note: Embedded structural header metadata generated by official financial institution statements is automatically stripped during preprocessing.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              <div v-if="uploading" class="text-center py-4">
                <div class="spinner-border text-primary spinner-border-sm mb-2"></div>
                <p class="apple-desc small mb-0">Analyzing document mapping structure...</p>
              </div>
            </div>

            <div v-else>
              <div class="apple-callout mb-4" :class="previewData.csv_type === 'skay' ? 'apple-callout-success' : 'apple-callout-warning'">
                <i class="bi" :class="previewData.csv_type === 'skay' ? 'bi-check-circle-fill text-success' : 'bi-exclamation-triangle-fill text-warning'"></i>
                <span class="text-white">{{ previewData.csv_type === 'skay' ? 'Skay structural matrix detected — auto-import initialized.' : 'Banking institution CSV structure detected — standard destination mapping required.' }}</span>
              </div>
              
              <div class="mb-4 p-3 apple-target-box" v-if="previewData.csv_type === 'bank'">
                <label class="apple-label">Target Destination Account</label>
                <select class="form-select apple-input" v-model="selectedAccount">
                  <option :value="null" disabled>-- Choose matching ledger account --</option>
                  <option v-for="acc in accounts" :key="acc.id" :value="acc.id">
                    {{ acc.name }} ({{ acc.balance.toFixed(2) }} €)
                  </option>
                </select>
                <div class="apple-desc mt-2 small">
                  Bank ledgers lack integrated structural metadata tags. Map incoming records to your target ledger framework manually.
                </div>
              </div>
              
              <div class="row g-3 mb-4">
                <div class="col-4">
                  <div class="apple-stat-card">
                    <span class="apple-stat-val">{{ previewData.total_rows }}</span>
                    <span class="apple-stat-lbl">Parsed Rows</span>
                  </div>
                </div>
                <div class="col-4">
                  <div class="apple-stat-card">
                    <span class="apple-stat-val">{{ previewData.columns.length }}</span>
                    <span class="apple-stat-lbl">Columns Detected</span>
                  </div>
                </div>
                <div class="col-4">
                  <div class="apple-stat-card">
                    <span class="apple-stat-val text-primary">
                      {{ previewData.csv_type.toUpperCase() }}
                    </span>
                    <span class="apple-stat-lbl">Parser Matrix</span>
                  </div>
                </div>
              </div>

              <label class="apple-label-sm">Data Parsing Table Preview (First 5 Rows)</label>
              <div class="table-responsive apple-table-container">
                <table class="table table-sm mb-0 align-middle apple-table">
                  <thead>
                    <tr>
                      <th v-for="col in previewData.columns" :key="col">
                        {{ col }}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="(row, idx) in previewData.preview" :key="idx">
                      <td v-for="col in previewData.columns" :key="col" class="text-truncate" style="max-width: 150px;">
                        {{ row[col] !== null ? row[col] : '-' }}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

          </div>
          
          <div class="modal-footer border-0 pt-3">
            <button type="button" class="apple-btn apple-btn-secondary" data-bs-dismiss="modal" :disabled="importing">Cancel</button>
            <button 
              v-if="previewData" 
              class="apple-btn apple-btn-primary" 
              @click="executeImport" 
              :disabled="importing || (!previewData.is_skay_format && !selectedAccount)"
            >
              <span v-if="importing" class="spinner-border spinner-border-sm me-2"></span>
              {{ importing ? 'Processing...' : 'Import Data' }}
            </button>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';
import { Modal } from 'bootstrap';
import { API_URL } from '../config';

export default {
  name: 'ImportCSV',
  data() {
    return {
      accounts: [],
      selectedAccount: null,
      file: null,
      uploading: false,
      previewData: null,
      importing: false,
      autoCreateCategories: true,
      autoCreateAccounts: true,
      modalInstance: null
    }
  },
  mounted() {
    this.loadAccounts();
    this.modalInstance = new Modal(this.$refs.modal);
  },
  methods: {
    async loadAccounts() {
      try {
        const response = await axios.get(`${API_URL}/accounts`);
        this.accounts = response.data;
      } catch (err) {
        console.error('Failed to fetch ledger accounts:', err);
      }
    },
    openModal() {
      this.resetState();
      this.loadAccounts();
      this.modalInstance.show();
    },
    resetState() {
      this.file = null;
      this.previewData = null;
      this.selectedAccount = null;
    },
    async handleFileUpload(event) {
      this.file = event.target.files[0];
      if (!this.file) return;
      
      this.uploading = true;
      const formData = new FormData();
      formData.append('file', this.file);
      
      try {
        const response = await axios.post(`${API_URL}/import/csv/preview`, formData, {
          headers: { 'Content-Type': 'multipart/form-data' }
        });
        this.previewData = response.data;
      } catch (err) {
        alert(err.response?.data?.detail || 'Failed to preview layout options.');
        this.file = null;
      } finally {
        this.uploading = false;
      }
    },
    async executeImport() {
      if (!this.previewData || !this.file) return;
      
      if (!this.previewData.is_skay_format && !this.selectedAccount) {
        alert('Please select a target account before submitting bank records.');
        return;
      }
      
      this.importing = true;
      const formData = new FormData();
      formData.append('file', this.file);
      
      const queryParams = {
        auto_create_categories: this.autoCreateCategories,
        auto_create_accounts: this.autoCreateAccounts,
        skip_duplicates: true
      };
      
      if (this.selectedAccount) {
        queryParams.target_account_id = this.selectedAccount;
      }
      
      try {
        const response = await axios.post(`${API_URL}/import/csv/execute`, formData, {
          headers: { 'Content-Type': 'multipart/form-data' },
          params: queryParams
        });
        
        const result = response.data;
        let msg = `Successfully imported: ${result.imported} transactions.`;
        if (result.skipped > 0) msg += `\nSkipped entries (duplicates): ${result.skipped}`;
        
        alert(msg);
        this.modalInstance.hide();
        this.$emit('imported');
      } catch (err) {
        alert('Import pipeline execution failed: ' + (err.response?.data?.detail || err.message));
      } finally {
        this.importing = false;
      }
    }
  }
}
</script>

<style scoped>
/* --- COEDIZIONE RIGIDA DARK COLOR PALETTE (iOS / macOS Standards) --- */

/* Contenitore Principale Modal */
.apple-modal {
  border-radius: 14px !important;
  border: 1px solid #2C2C2E !important;
  background-color: #1C1C1E !important; /* Sfondo scuro Apple nativo */
  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.5) !important;
  padding: 8px;
}

/* Tipografia */
.apple-title {
  color: #FFFFFF !important;
  font-weight: 600 !important;
  font-size: 1.15rem;
}
.apple-label {
  font-size: 0.85rem;
  font-weight: 500;
  color: #FFFFFF !important;
  margin-bottom: 6px;
}
.apple-label-sm {
  font-size: 0.75rem;
  font-weight: 600;
  color: #8E8E93 !important;
  text-transform: uppercase;
  letter-spacing: 0.03em;
  margin-bottom: 8px;
}
.apple-desc {
  font-size: 0.84rem;
  color: #AEAEB2 !important; /* Grigio chiaro da lettura Apple */
  line-height: 1.4;
}
.apple-text-warning {
  color: #FF9500 !important;
}

/* Input Fields & Select Scuri */
.apple-input {
  border-radius: 10px !important;
  border: 1px solid #3A3A3C !important;
  background-color: #2C2C2E !important;
  color: #FFFFFF !important;
  font-size: 0.9rem;
  padding: 10px 14px;
}
.apple-input:focus {
  border-color: #0A84FF !important;
  box-shadow: 0 0 0 3px rgba(10, 132, 255, 0.2) !important;
  background-color: #2C2C2E !important;
  color: #FFFFFF !important;
}
.apple-input option {
  background-color: #2C2C2E !important;
  color: #FFFFFF !important;
}

/* Pulsanti stile iOS */
.apple-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  font-size: 0.88rem;
  font-weight: 500;
  padding: 10px 18px;
  border-radius: 10px;
  border: none;
  cursor: pointer;
  transition: opacity 0.15s ease;
}
.apple-btn:active {
  opacity: 0.8;
}
.apple-btn-primary {
  background-color: #0A84FF !important; /* Blue Apple Dark */
  color: #FFFFFF !important;
}
.apple-btn-primary:disabled {
  background-color: #3A3A3C !important;
  color: #8E8E93 !important;
  cursor: not-allowed;
}
.apple-btn-secondary {
  background-color: #2C2C2E !important;
  color: #FFFFFF !important;
  border: 1px solid #3A3A3C !important;
}
.apple-btn-secondary:hover {
  background-color: #3A3A3C !important;
}

/* FIX DEFINITIVO ACCORDION (Nessuno sfondo bianco residuo) */
.apple-accordion {
  background-color: #2C2C2E !important;
  border: 1px solid #3A3A3C !important;
  border-radius: 10px !important;
  overflow: hidden;
}
.apple-accordion-trigger {
  background-color: #2C2C2E !important;
  color: #FFFFFF !important;
  font-size: 0.88rem !important;
  font-weight: 500 !important;
  border: none !important;
  box-shadow: none !important;
  padding: 14px !important;
}
.apple-accordion-trigger:not(.collapsed) {
  color: #0A84FF !important;
  background-color: #2C2C2E !important;
  border-bottom: 1px solid #3A3A3C !important;
}
.apple-accordion-trigger::after {
  filter: invert(1) brightness(2) !important; /* Forza la freccia a diventare bianca */
}
.apple-accordion-content {
  background-color: #1C1C1E !important;
  color: #AEAEB2 !important;
  padding: 16px !important;
  border: none !important;
}

/* Callouts minimali */
.apple-callout {
  display: flex;
  align-items: flex-start;
  padding: 12px 14px;
  border-radius: 10px;
  font-size: 0.84rem;
  line-height: 1.4;
  background-color: #2C2C2E !important;
  color: #AEAEB2 !important;
  border: 1px solid #3A3A3C !important;
}
.apple-callout-info { border-left: 4px solid #0A84FF !important; }
.apple-callout-info i { color: #0A84FF; }
.apple-callout-success { border-left: 4px solid #30D158 !important; }
.apple-callout-warning { border-left: 4px solid #FF9500 !important; }

/* Box di mappatura e Grid Card */
.apple-target-box {
  background-color: #2C2C2E !important;
  border: 1px solid #3A3A3C !important;
  border-radius: 10px;
}
.apple-stat-card {
  background-color: #2C2C2E !important;
  border: 1px solid #3A3A3C !important;
  border-radius: 10px;
  padding: 12px;
  text-align: center;
  display: flex;
  flex-direction: column;
}
.apple-stat-val {
  font-size: 1.3rem;
  font-weight: 600;
  color: #FFFFFF !important;
  letter-spacing: -0.02em;
}
.apple-stat-lbl {
  font-size: 0.72rem;
  color: #8E8E93 !important;
  margin-top: 2px;
}

/* Tabella Anteprima Dati */
.apple-table-container {
  border: 1px solid #3A3A3C !important;
  border-radius: 10px;
  background-color: #1C1C1E !important;
  max-height: 220px;
  overflow-y: auto;
}
.apple-table {
  background-color: #1C1C1E !important;
  margin-bottom: 0 !important;
}
.apple-table thead th {
  background-color: #2C2C2E !important;
  color: #FFFFFF !important;
  font-weight: 600;
  font-size: 0.8rem;
  padding: 10px 12px;
  border-bottom: 1px solid #3A3A3C !important;
  position: sticky;
  top: 0;
  z-index: 5;
}
.apple-table tbody tr {
  background-color: #1C1C1E !important;
}
.apple-table tbody tr:hover td {
  background-color: rgba(255, 255, 255, 0.04) !important;
}
.apple-table tbody td {
  padding: 10px 12px !important;
  color: #AEAEB2 !important;
  font-size: 0.8rem;
  border-bottom: 1px solid #2C2C2E !important;
  background-color: transparent !important;
}

/* Elementi di servizio minori */
.apple-badge {
  display: inline-block;
  font-size: 0.7rem;
  font-weight: 600;
  text-transform: uppercase;
  padding: 2px 6px;
  background: #3A3A3C;
  border-radius: 4px;
  color: #FFFFFF;
}
.apple-close-btn {
  filter: invert(1) brightness(2) !important;
  opacity: 0.7;
}

/* Scrollbar Custom */
.apple-table-container::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}
.apple-table-container::-webkit-scrollbar-thumb {
  background-color: #3A3A3C;
  border-radius: 10px;
}
</style>