<template>
  <div class="modal fade" ref="login2FAModal" data-bs-backdrop="static" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
      <div class="modal-content border-0 shadow">
        <div class="modal-header bg-primary text-white py-3">
          <h5 class="modal-title fw-bold">2FA Verification Required</h5>
        </div>
        <div class="modal-body p-4 text-center">
          <p class="small text-muted">Enter the 6-digit code generated by your authenticator app:</p>
          <input type="text" class="form-control text-center fs-2 fw-bold tracking-wider" 
                 v-model="loginOtpCode" maxlength="6" placeholder="000000" @keyup.enter="submit2FALogin">
        </div>
        <div class="modal-footer border-0 p-3 bg-light">
          <button type="button" class="btn btn-primary w-100 fw-bold py-2" @click="submit2FALogin" :disabled="loginVerifying || loginOtpCode.length !== 6">
            {{ loginVerifying ? 'Verifying...' : 'Verify' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';
import { Modal } from 'bootstrap';
import { API_URL } from '../config';

export default {
  name: 'TwoFactorLoginModal',
  data() {
    return {
      loginOtpCode: '',
      loginVerifying: false,
      tempToken: null,
      modalInstance: null
    };
  },
  mounted() {
    this.modalInstance = new Modal(this.$refs.login2FAModal);
  },
  beforeUnmount() {
    if (this.modalInstance) this.modalInstance.dispose();
  },
  methods: {
    // External trigger method called from the parent Login component
    show(tempToken) {
      this.tempToken = tempToken;
      this.loginOtpCode = '';
      this.modalInstance.show();
    },
    async submit2FALogin() {
      this.loginVerifying = true;
      try {
        const response = await axios.post(`${API_URL}/auth/2fa/login`, {
          temp_token: this.tempToken,
          otp_token: this.loginOtpCode
        });
        localStorage.setItem('token', response.data.access_token);
        this.modalInstance.hide();
        this.$root.showToast('Login successful!', 'success');
        this.$router.push('/dashboard');
      } catch (err) {
        this.$root.showToast('Invalid or expired verification code', 'danger');
      } finally {
        this.loginVerifying = false;
      }
    }
  }
};
</script>